POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InllZWhhd0BleGFtcGxlLmNvbSIsImlkIjoyLCJpYXQiOjE2OTEwNzYzNjh9.9Fi6H9kUWzpQFLxRLuzUeP-uGHEKZnJkhBGzJM4UOKI

{
  "author": "Somebody",
  "url": "example.com",
  "title": "New article",
  "likes": 6,
  "year": 2023
}
