POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhc3NpQGV4YW1wbGUuY29tIiwiaWQiOjEyLCJpYXQiOjE2OTEwNjMxNzN9.Qp9Qm-M1_ViubFnb646PIvpm0-kmm8X4HMGnc1frWkc

{
  "author": "Somebody",
  "url": "example.com",
  "title": "You can find things here",
  "likes": 1
}
